#⇓1ならいい0ならだめ
turn: 1
#1なら出力0なら出力しない
debug_log: 1
sakes:
  "◇§9無限水源":
    name: "◇§9無限水源"
    price: 100000
    description:
      - "§f水が無限に出てくる水源"
    probability: 10
    nannbunnnonannka: 4
    get_price: 90000
    expectation: "§e§l??????"
    mugen: true
    Color_R: 30
    Color_G: 144
    Color_B: 255

  "§fビーコネーター":
    name: "§fビーコネーター"
    price: 123456
    description:
      - "採掘が捗りそう…"
    probability: 100
    nannbunnnonannka: 9
    get_price: 1234567
    expectation: "☆☆☆☆★"
    Color_R: 255
    Color_G: 255
    Color_B: 255
    commands:
      - "effect give [name] haste 2 10"